project_id = "yfcxdbhrtjdmwyifgptf"

[functions.generate-lote-hashes]
verify_jwt = false

[functions.migrar-eventos-historicos]
verify_jwt = false

[functions.restore-belt-state]
verify_jwt = false

[functions.finalizar-manutencao-semanal]
verify_jwt = false

[functions.corrigir-status-lote]
verify_jwt = false

[functions.reativar-lote-entregas]
verify_jwt = false
