project_id = "yfcxdbhrtjdmwyifgptf"

[functions.generate-lote-hashes]
verify_jwt = false

[functions.migrar-eventos-historicos]
verify_jwt = false

[functions.restore-belt-state]
verify_jwt = false

[functions.finalizar-manutencao-semanal]
verify_jwt = false

[functions.corrigir-status-lote]
verify_jwt = false

[functions.reativar-lote-entregas]
verify_jwt = false

[functions.coleta-diaria-sensores]
verify_jwt = false

[functions.coleta-diaria-sensores.schedule]
cron = "0 23 * * *"

[functions.calcular-medias-sensores]
verify_jwt = false

[functions.testar-tago-io]
verify_jwt = false
