project_id = "yfcxdbhrtjdmwyifgptf"

[functions.generate-lote-hashes]
verify_jwt = false

[functions.migrar-eventos-historicos]
verify_jwt = false

[functions.migrar-eventos-lote]
verify_jwt = false

[functions.finalizar-manutencao-semanal]
verify_jwt = false