// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfcxdbhrtjdmwyifgptf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmY3hkYmhydGpkbXd5aWZncHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTc0NzMsImV4cCI6MjA2ODg3MzQ3M30.Gn_xSbORlNC8nMepQSmvLrXsKXYpGQGcPHOfIO3zhvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});